# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='landing_page',
            new_name='Graduation_pictures',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='favourite_moments',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='mc_class',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='live_link',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='content',
            new_name='group_of_the_year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design',
        ),
        migrations.RemoveField(
            model_name='project',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usability',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='design',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='usability',
        ),
    ]
