# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0002_auto_20190711_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='technologies',
        ),
    ]
