# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0003_auto_20190711_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologies', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='favourite_moments',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Graduation_pictures',
            new_name='landing_page',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='year',
            new_name='live_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='mc_class',
            new_name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='design',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(to='yearapp.categories'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='yearapp.technologies'),
        ),
    ]
