# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0004_auto_20190711_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='group_of_the_year',
            new_name='content',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='creativity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='overall',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='usability',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='creativity',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='design',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='usability',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
