# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0005_auto_20190711_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='Favourite_moment',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='class_of_the_year',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='landing_page',
            new_name='graduation_pictures',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='mc_class',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='content',
            new_name='class_of_the_year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='project',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usability',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='design',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='usability',
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='technologies',
        ),
    ]
