# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0006_auto_20190711_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Favourite_moment',
            new_name='Theme_of_the_year',
        ),
    ]
