# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0010_auto_20190711_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='class_of_the_year',
            new_name='content',
        ),
        migrations.AddField(
            model_name='project',
            name='creativity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='design',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='usability',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
