# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0012_auto_20190711_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='landing_page',
            new_name='upload_your_images_here',
        ),
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='technologies',
        ),
    ]
