# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0013_auto_20190711_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='upload_your_images_here',
            new_name='landing_page',
        ),
    ]
