# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0015_auto_20190711_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='Theme_of_the_year',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='mc_class',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='class_of_the_year',
            field=models.CharField(max_length=255),
        ),
    ]
