# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0016_auto_20190711_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Theme_of_the_year',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='mc_class',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='upload_your_images_here',
            new_name='upload_your_images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='class_of_the_year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
