# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0017_auto_20190711_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='upload_your_images',
            new_name='upload_your_images_here',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
    ]
