# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0018_auto_20190711_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='mc_class',
        ),
    ]
