# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearapp', '0019_auto_20190711_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='mc_class',
            new_name='title',
        ),
    ]
